# What is NumPy?
Python has:

Lists (costless insertion and append), dictionaries (fast lookup).
High-level number objects: integers, floating point.

NumPy is:

Extension package to Python for multi-dimensional arrays.
Closer to hardware (efficiency).
Designed for scientific computation (convenience).


### Multi-dimensional arrays
Memory-efficient container that provides fast numerical operations.

####  Example data:

Values of an experiment/simulation at discrete time steps.
Signal recorded by a measurement device, e.g. sound wave.
Pixels of an image, grey-level or colour.
3D data measured at different X-Y-Z positions, e.g. MRI scan.
...


How to use NumPy
---

### 1) As a normal Python package

Convention is to import the package as `np`.




In [1]:
! pip install numpy

In [2]:
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, etc.).
  

In [3]:
import numpy as np 
a=np.array([0,1,2,3])
print(a)
print(type(a))
print(id(a))
b=a
print(id(b))

[0 1 2 3]
<class 'numpy.ndarray'>
2447001607536
2447001607536


NumPy arrays
===

One-dimensional arrays
---

In [4]:
a=np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [5]:
a=np.array([0,1,2,3])
print(a)
print(a.ndim)
print(a.shape)
b=np.array([[0],[1],[2]])
print(b)
print(b.ndim)
print(b.shape)

[0 1 2 3]
1
(4,)
[[0]
 [1]
 [2]]
2
(3, 1)


In [8]:
len(a)

4

NumPy arrays
===

Multi-dimensional arrays
---

In [11]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b)
print()
c=np.array([[[1,2],[3,4]],[[1,1],[2,2]]])
print(c)
print(c.ndim)
print(c.shape)
print(len(c))

[[1 2 3]
 [4 5 6]]

[[[1 2]
  [3 4]]

 [[1 1]
  [2 2]]]
3
(2, 2, 2)
2


In [12]:
b.ndim

2

In [13]:
b.shape

(2, 3)

In [14]:
len(b)

2

In [18]:
import numpy as np
print(np.array([[1.0,2],[3,4]]))
print()
print(np.array([1,2,"a"]))
print()
z=np.array([1,2,3],"complex",ndmin=5, copy=False)
y=z
print(id(y))
print(id(z))
print(z)
z1=np.mat([[1,2,3],[4,5,6]])
print(z1)


[[1. 2.]
 [3. 4.]]

['1' '2' 'a']

2447006384272
2447006384272
[[[[[1.+0.j 2.+0.j 3.+0.j]]]]]
[[1 2 3]
 [4 5 6]]


In [19]:
import numpy as np
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warning sections 

In [24]:
import numpy as np
print(np.arange(1,11))
print()
print()
print(np.arange(3.0))
print()
print()
print(np.arange(1,10,2))
print()
print()
print(np.arange(20,dtype="complex"))
print()
print()
print(np.arange(1,10,2,"float"))

[ 1  2  3  4  5  6  7  8  9 10]


[0. 1. 2.]


[1 3 5 7 9]


[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 17.+0.j
 18.+0.j 19.+0.j]


[1. 3. 5. 7. 9.]


NumPy arrays
===

Series
---

Evenly spaced (like the Python `range` builtin):

In [25]:
import numpy as np 
print(np.arange(1,9,2))
print(np.arange(1,2,6))

[1 3 5 7]
[1]


In [26]:
import numpy as np
print(np.linspace(0,1,6)) # It divides the values in equal no of parts specified 

[0.  0.2 0.4 0.6 0.8 1. ]


In [27]:
np.linspace(0,1,6,endpoint=False)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333])

NumPy arrays
===

Common arrays (1/2)
---

In [28]:
import numpy as np 
help (np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.

In [29]:
import numpy as np 
print(np.ones(8))
print(np.ones(7,dtype="int"))
print()

print(np.ones((3,4)))
print()
print()
print(np.ones(((1,2,3)),dtype="int"))

[1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[[1 1 1]
  [1 1 1]]]


In [30]:
import numpy as np
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, without initializing entries.

    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via thi

In [34]:
import numpy as np 
print(np.empty(6,dtype=int))
print()
print(np.empty([2, 2], dtype=int))

[1 1 1 1 1 1]

[[1 3]
 [5 7]]


In [32]:
import numpy as np 

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
import numpy as np
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [36]:
import numpy as np 
print(np.zeros(5))
print()
print()
print(np.zeros(3,dtype="int"))
print()
print(np.zeros((2,3)))
print()
print(np.zeros([3,4]))
print()
print(np.zeros(4,order="F"))
print()
print(np.zeros(4,order="C"))
print()
print(np.zeros((3,4),order="F"))

[0. 0. 0. 0. 0.]


[0 0 0]

[[0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0. 0. 0. 0.]

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
help(np.asarray)

Help on built-in function asarray in module numpy:

asarray(...)
    asarray(a, dtype=None, order=None, *, like=None)

    Convert the input to an array.

    Parameters
    ----------
    a : array_like
        Input data, in any form that can be converted to an array.  This
        includes lists, lists of tuples, tuples, tuples of tuples, tuples
        of lists and ndarrays.
    dtype : data-type, optional
        By default, the data-type is inferred from the input data.
    order : {'C', 'F', 'A', 'K'}, optional
        Memory layout.  'A' and 'K' depend on the order of input array a.
        'C' row-major (C-style),
        'F' column-major (Fortran-style) memory representation.
        'A' (any) means 'F' if `a` is Fortran contiguous, 'C' otherwise
        'K' (keep) preserve input order
        Defaults to 'K'.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supp

In [42]:
print(np.asarray([1, 2, 3]))
print(np.array([1, 2, 3]))
print(np.asarray(["a", 2, 3]))
print(np.array(["a", 2, 3]))



[1 2 3]
[1 2 3]
['a' '2' '3']
['a' '2' '3']


In [37]:
import numpy as np 
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [38]:
import numpy as np 
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

In [43]:
import numpy as np
print(np.linspace(1,2, retstep=True))
print()
print(np.linspace(1,100,num=5,retstep=True))
print()
a=np.linspace(1,100,num=5,endpoint=False,retstep=True)
print(a)
print(a[0][0])
np.linspace(1,100,num=5,retstep=True)
np.linspace(1,100,num=5,dtype=int)

(array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ]), 0.02040816326530612)

(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), 24.75)

(array([ 1. , 20.8, 40.6, 60.4, 80.2]), 19.8)
1.0


array([  1,  25,  50,  75, 100])

In [44]:
import numpy as np 
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.

    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.

        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_func

In [45]:
import numpy as np 
print(np.eye(5))
print()
print(np.eye(2,3))
print()
print(np.eye(3,3))
print()
print(np.eye(4,k=-3))
print()
print(np.eye(5,k=2))
print()
print(np.eye(2,3))
print()
print(np.eye(5,dtype=int))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [46]:
import numpy as np
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.

    The identity array is a square array with ones on
    the main diagonal.

    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.

    Examples
    --------
    >>> np.identity(3)
    array([[1.,  0.,  0.

In [47]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [48]:
import numpy as np 
print(np.diag(np.array([1,2,3,4])))# It prints a diagonal matrix with the elements listed as the diagonal values


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]




Random numbers
---

Random samples from a uniform distribution over $[0, 1)$:

In [49]:
import numpy as np 

np.random.rand(4)

array([0.76985393, 0.31264819, 0.35895337, 0.17061143])

#### Creating a Vector

In [50]:
import numpy as np 
vec_row=np.array([1,2,3])
vec_col=np.array([[1],[2],[3]])
print("The row vector is as follow : ",vec_row)
print("The column vector is as follow : ",vec_col)

The row vector is as follow :  [1 2 3]
The column vector is as follow :  [[1]
 [2]
 [3]]


#### Creating a Matrix

In [52]:
import numpy as np 
matrix=np.array([[1,2],[3,4],[5,6]])
print(type(matrix))
matrix=np.mat([[1,2],[3,4],[5,6]])
print(type(matrix))


<class 'numpy.ndarray'>
<class 'numpy.matrix'>


#### Creating a Sparse Matrix

In [54]:
import numpy as np 
from scipy import sparse
matrix=np.mat([[0,0,0,0,0],[1,1,0,0,0],[3,0,0,3,0]])
sparse_matrix=sparse.csr_matrix(matrix) #It is a compressed Sparse matrix 
print(matrix)
print(sparse_matrix) # The output will have the position of the element and the element too

[[0 0 0 0 0]
 [1 1 0 0 0]
 [3 0 0 3 0]]
  (1, 0)	1
  (1, 1)	1
  (2, 0)	3
  (2, 3)	3


In [55]:
import numpy as np 
vector=np.array([1,2,3,4,5,6])
print(vector)# will print the complete vector 
print()
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)# will print the complete matrix
print()
print(vector[2])# Will print the value at index 2
print()
print(matrix[1,1])# Will print the value of 1st row ,1st column
print()
print(vector[:]) # Will print the complete vector 
print()
print(vector[:2])# Will print the value till index 1 
print()
print(vector[2:])# will print the value from 2 index onwards
print()
print(matrix[:2,:])# Select first 2 rows and all columns of the matrix
print()
print(matrix[:,1:2])# It will print all rows and column no 1
print()

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

3

5

[1 2 3 4 5 6]

[1 2]

[3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[2]
 [5]
 [8]]



### Descrbing the Matrix

In [56]:
import numpy as np 
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("The shape of matrix is  :",matrix.shape) # Prints the dimension or shape of the matrix

print()

print("The size of matrix is  :",matrix.size)# It prints the no of elements in the matrix its actually 
# no of (rows*columns)

print()
print("The dimension of matrix is  :",matrix.ndim)# It prints the dimension of the matrix

The shape of matrix is  : (3, 3)

The size of matrix is  : 9

The dimension of matrix is  : 2


#### Applying operations on the matrix elements


In [57]:
import numpy as np 
matrix =np.mat([[1,2,3],[3,3,2],[4,5,6]])
add_100 =lambda i:i+100
vectorized_mat=np.vectorize(add_100) # create a vectorize variable
vectorized_mat(matrix) #Apply the vectorization effect on the defined matrix

matrix([[101, 102, 103],
        [103, 103, 102],
        [104, 105, 106]])

#### Finding Maximum and Minimum Values


In [58]:
import numpy as np 
matrix=np.mat([[1,2,3],[4,5,6],[7,8,9]])
print("The maximum value is  :",np.max(matrix))# Returns the maximum element of the matrix
print("The minimum value is  :",np.min(matrix))# Returns the minimum elemnt of the matrix

The maximum value is  : 9
The minimum value is  : 1


### axis
Using the axis parameter we can also apply the operation along a certain axis:<br>
axis=0 means on each column <br>
axis=1 means on each row

In [60]:
import numpy as np 
matrix=np.mat([[1,2,3],[1,0,1],[2,0,0]])
print(matrix)
print("The maximum value is  :",np.max(matrix,axis=0))# Returns the maximum element of the matrix
print("The minimum value is  :",np.min(matrix,axis=0))
print("The maximum value is  :",np.max(matrix,axis=1))# Returns the maximum element of the matrix
print("The minimum value is  :",np.min(matrix,axis=1))

[[1 2 3]
 [1 0 1]
 [2 0 0]]
The maximum value is  : [[2 2 3]]
The minimum value is  : [[1 0 0]]
The maximum value is  : [[3]
 [1]
 [2]]
The minimum value is  : [[1]
 [0]
 [0]]


### Calculating Average Variance and Standard Deviation 


In [61]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The mean of the matrix is :" ,np.mean(matrix))# It will give the mean of the matrix
print()
print("The variance of the matrix is :" ,np.var(matrix))# It will give the variance of the matrix
print()
print("The standard deviation of the matrix is :" ,np.std(matrix))# It will give the standard Deviation of the matrix

The mean of the matrix is : 5.0

The variance of the matrix is : 6.666666666666667

The standard deviation of the matrix is : 2.581988897471611


### Reshaping of the arrays or matrix

In [65]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matrix)
print(matrix.reshape(6,2))# Change the shape of the matrix
print()
print(matrix.reshape(2,6))# Change the shape of the matrix
print()
print(matrix.reshape(1, -1))# Change it to 2 D row array
print()
print(matrix.reshape(12))# provides a row array of 1 D
print()
print(matrix.reshape(-1))# provides a row array of 1 D

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Transposing a vector or matrix

In [66]:
import numpy as np 
matr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The original Matrix is :\n", matr)
print()
print("The Transposed Matrix is :\n",matr.T)
print()

The original Matrix is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

The Transposed Matrix is :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]



In [68]:
import numpy as np
def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    print(a)
    print(b)    
    c = a + b
    return c
print(numpysum(10))

[ 0  1  4  9 16 25 36 49 64 81]
[  0   1   8  27  64 125 216 343 512 729]
[  0   2  12  36  80 150 252 392 576 810]


In [69]:
import numpy as np
myarray=np.mat([[1,2,3,4],[5,6,7,8]],dtype=np.int64)
print(myarray)

[[1 2 3 4]
 [5 6 7 8]]


#### To create a np arrays using lists

In [70]:
import numpy as np
alist=["a","jay",8] # Define a list 
arr=np.array(alist) # conver a list to array
print(arr)# print the array
print(arr.dtype)# prints the data type for more information refer numpy documentation
print(arr.ndim) # Provides the dimension of the array
print(arr.shape)# if it is 1 D then you will just get the number of values as a tuple

['a' 'jay' '8']
<U11
1
(3,)


#### To create a Matrix

In [ ]:
arr_l=[[[1,2,3],[3,4,5],[6,7,8]],[[1,2,1],[3,2,3],[2,2,2]]]# Define a list of values 
matr=np.array(arr_l) # convert it into matrix 
#print(arr_l)
print(matr)# print matrix
#matr
print(matr.dtype)# print the data type of matrix
#matr.dtype
print(matr.ndim) # print the dimension of matrix
#matr.ndim
print(matr.shape) # print the shape of matrix
#matr.shape

### Creating Numpy Arrays using arange() built-in function
arange([start,] stop[, step,], dtype=None)<br>
Return evenly spaced values within a given interval.<br>
Values are generated within the half-open interval ``[start, stop)``<br>
(in other words, the interval including `start` but excluding `stop`).<br>
can only create a vector

In [ ]:
arl=np.arange(20)# Create a range of element 
print(arl)# 

In [ ]:
arr1=np.arange(1,20)
print(arr1)
arr2=np.arange(1,20,2)
print(arr2)

In [71]:
arr4 =np.arange(41,20,-2,dtype="float32")
# Here the start value is 41 end value is 20 decrement by 2 and the datatype is float
print(arr4)

[41. 39. 37. 35. 33. 31. 29. 27. 25. 23. 21.]


In [ ]:
arr7=np.zeros(4)# Print the vectors of zeros
print(arr7)
print(arr7.shape) # It gives the number of element or the shape 

In [ ]:
arr6=np.zeros((4,6),dtype="int32") # create a matrix of zeros in 4 by 6 
print(arr6)
print(arr6.ndim)

In [ ]:
ar1=np.ones((2,3),dtype="int64")# creates an array of ones in 2 by 3 matrix
print(ar1)
print(ar1.shape)


### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)<br>
Return evenly spaced numbers between the specified interval<br>
takes avg of numbers given and gives values using that can create only vectors<br>

In [ ]:
arr=np.linspace(1,100,10)# start number,end number, no of parts to be made
print(arr)

### np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')<br>
Return a 2-D array with ones on the diagonal and zeros elsewhere.r

In [ ]:
arrs=np.eye(4)# eye function create a 2 D 
print(arrs)

In [72]:
#rand(d0, d1, ..., dn)
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
arr_r1=np.random.rand(10)#(10)
arr_r2=np.random.rand(3,3)
print(arr_r1)
print (arr_r2)

[0.43497483 0.70072864 0.69021818 0.2838339  0.68183073 0.6998749
 0.69833572 0.10689401 0.81331016 0.62105616]
[[0.97066601 0.88259905 0.59136853]
 [0.75145384 0.58668981 0.86482858]
 [0.25800165 0.24316341 0.97894279]]


In [73]:
import numpy as np#Return a sample (or samples) from the "standard normal" distribution;concentrated around zeros
arr_r3=np.random.randn(3)#(3)
arr_r2=np.random.randn(4,2)
print(arr_r2)
print(arr_r3)

[[-0.96595734 -0.95765381]
 [-1.9062668   0.29601684]
 [-0.18809     0.60159107]
 [ 0.0517469   0.21993231]]
[-0.85221466  0.55500886 -0.19349004]


#### randint(low, high=None, size=None, dtype='l')<br>
Return random integers from `low` (inclusive) to `high` (exclusive).<br>
Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). <br>If
`high` is None (the default), then results are from [0, `low`).arr_r3=np.random.randint(2,20,10)


In [78]:
arr_r3=np.random.randint(10)#(2,20,10),(2,20)
arr_r4=np.random.randint(2,20,10)
arr_r5=np.random.randint(2,20)
# single value will act as end
#two values are start and end
# three values are start, end and iteration
print(arr_r3)
print(arr_r4)
print(arr_r5)

7
[12  2  2  5  6  6 12  7  5  2]
12


## TASK

#### Which among the following will produce the same result as:
1. np.linspace(1,10,10,dtype='int32')
2. np.arange(1,11)
3. np.random.randint(1,11)
4. np.array(range(1,11))

In [ ]:

print(np.linspace(1,10,10,dtype='int32'))
print()
print(np.arange(1,11))
print()
print(np.random.randint(1,11))
print()
print(np.array(range(1,11)))

### Conversion and other function

In [ ]:
#Converting a 1-D array to a 2-D array using reshape() 
#Returns an array containing the same data with a new shape.
arr_co1=np.linspace(20,30,6,dtype='int32')
print(arr_co1.reshape(6))#(2,3)
print(arr_co1.reshape(2,3))#(2,3)
print()
print()
x=np.random.randint(5,10,(2,3))
print(x)
print()
y=x.reshape(3,2)
print(y)

In [79]:
arr_co2=np.arange(20).reshape(2,10)
#arr_co2=np.arange(1,21).reshape(2,10)
print(arr_co2)
print(arr_co2.max())#axis=None is default gives max value
print(arr_co2.min())# gives min value
print(arr_co2.argmax())# gives the value at which maximum value from the function is attend
print(arr_co2.argmin())# gives the value at which minimum value from the function is attend

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
19
0
19
0


In [80]:
a=np.random.randint(10,100,(2,3))# Creates a 2 by 3 matrix of values between 10 and 1000
print(a)
print()
print()
print(a.max(axis=1))#axis=0/1(row)
print()
print()
print(a.min(axis=0))# columnwise
print()
print()
print(a.argmax(axis=1)) #
print()
print()
print(a.argmax(axis=0))#

[[69 56 54]
 [53 76 91]]


[69 91]


[53 56 54]


[0 2]


[0 1 1]


### Indexing

In [95]:
a=[1,2,3,4,5]
print(a)
a[1]

[1, 2, 3, 4, 5]


2

In [96]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[1])
print(arr[1,2])
print(arr[1:,0:2])# starts from second row and considers first two column
print(arr[:2,1:])# first two rows and last two columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6
[[4 5]
 [7 8]]
[[2 3]
 [5 6]]


In [97]:
#Conditional and Logical selection 
ar=[[34,23,56,78],[76,98,6,3],[23,54,77,45]]
ar=np.array(ar)
ar>70 # Compares the 70 with each of the value and depending on condition returns true or false.


array([[False, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [98]:
print(ar[(ar>70)])# provides all values which are greater than 70
print(ar[(ar>30) & (ar<70)])# performs and operation
print(ar[(ar>30) | (ar==70)])# performs or operation

[78 76 98 77]
[34 56 54 45]
[34 56 78 76 98 54 77 45]


### Fancy Indexing

In [99]:
import numpy as np 
arr_height1=np.array([173,185,186,172,165,184,176])
print(arr_height1[3],arr_height1[5],arr_height1[6])

172 184 176


In [100]:
ind=[3,5,6]  # fancy indexing
print(arr_height1[ind])#fancy index

[172 184 176]


In [101]:
arr=np.array([[10,20,30],[70,80,90],[40,50,60]])
print(arr)
print()
row=[0,0,2]
col=[2,1,0]
print(arr[row,col])
print()
print(arr[2,col])
print()
print(arr[1:,col])
arr[1:,col]=100
arr

[[10 20 30]
 [70 80 90]
 [40 50 60]]

[30 20 40]

[60 50 40]

[[90 80 70]
 [60 50 40]]


array([[ 10,  20,  30],
       [100, 100, 100],
       [100, 100, 100]])

In [102]:
# Conditional and Logical Selection 
import numpy as np 
arr2=[[32,22,45,34],[12,45,67,87],[21,41,52,67]]
arr2=np.array(arr2)
arr2>40
print(arr2>40)

[[False False  True False]
 [False  True  True  True]
 [False  True  True  True]]


In [103]:
print(arr2[(arr2>40)])
print(arr2[(arr2>30) &(arr2<70)])
print(arr2[(arr2>30)|(arr2==67)])

[45 45 67 87 41 52 67]
[32 45 34 45 67 41 52 67]
[32 45 34 45 67 87 41 52 67]


In [104]:
import numpy as np 
arr3=np.array([23,54,65,77])
ar4=np.array([13,43,56,77])
ar5=np.array([13,43,56,77])
ar_eq=np.allclose(arr3,ar4)
ar_e=np.allclose(ar4,ar5)
print(ar_eq)
print(ar_e)
arr3=np.array([np.nan,54,65,77])
ar4=np.array([np.nan,54,65,77])
ar_eo=np.allclose(arr3,ar4)
print(ar_eo)

False
True
False


In [106]:
#Broadcasting: to change multiple elements at once
arr3=np.array([[23,54,65,77]])
print(arr3)
arr3[:2,:2]=40
print()
print(arr3)

[[23 54 65 77]]

[[40 40 65 77]]


In [107]:
a=np.array([1,2,3],float)
print(a)
print(a.tolist())
st=a.tobytes()
print(st)


[1. 2. 3.]
[1.0, 2.0, 3.0]
b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'


In [110]:
import numpy as np 
b=np.array([1,2,3],float)
print(b)
b.fill(10)

print()
print(b)

[1. 2. 3.]

[10. 10. 10.]


Transposed versions of arrays can also be generated, which will create a new array with the
final two axes switched:

In [111]:
a=np.array(range(6),float).reshape((2,3))
print(a)
a.transpose()

[[0. 1. 2.]
 [3. 4. 5.]]


array([[0., 3.],
       [1., 4.],
       [2., 5.]])

One-dimensional versions of multi-dimensional arrays can be generated with flatten:

In [112]:
b=np.array([[1,2,3],[4,5,6]],float)
print(b)
print(b.flatten())


[[1. 2. 3.]
 [4. 5. 6.]]
[1. 2. 3. 4. 5. 6.]


Two or more arrays can be concatenated together using the concatenate function with a
tuple of the arrays to be joined:

In [113]:
a=np.array([1,2],float)
b=np.array([3,4,5,6],float)
c=np.array([7,8,9],float)
np.concatenate((a,b,c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [114]:
a=np.array([[1,2],[3,4]],float)
b=np.array([[5,6],[8,0]],float)
print(np.concatenate((a,b)))
print()
print(np.concatenate((a,b),axis=0))
print()
print(np.concatenate((a,b),axis=1))

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [8. 0.]]

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [8. 0.]]

[[1. 2. 5. 6.]
 [3. 4. 8. 0.]]


Finally, the dimensionality of an array can be increased using the newaxis constant in bracket notation:

In [115]:
a=np.array([1,2,3],float)
print(a)
print()
print()
print(a[:,np.newaxis])
print()
print()
print(a[:,np.newaxis].shape)
print()
print()
print(a[np.newaxis,:])
print()
print()
print(a[np.newaxis,:].shape)

[1. 2. 3.]


[[1.]
 [2.]
 [3.]]


(3, 1)


[[1. 2. 3.]]


(1, 3)
